spring:
  application:
    name: conhub-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KarolWojtas/conhub-config-file-repo.git
      
server:
  port: 8888


          